[build]
publish = "."
functions = "netlify/functions"

[context.production]
  branch = "main"

[context.staging]
  branch = "staging"

[[redirects]]
  from = "/mentorship"
  to = "/mentorship/dashboard/"
  status = 301

[[redirects]]
  from = "/mentorship/dashboard"
  to = "/mentorship/dashboard/"
  status = 301

[[redirects]]
  from = "/mentorship/mentor-portal"
  to = "/mentorship/mentor-portal/"
  status = 301
