import React from 'react';
import { Audio, interpolate, staticFile, useCurrentFrame } from 'remotion';
import { SCENES } from '../primitives/palette';

/**
 * Placeholder music bed (public/music/bed.wav, generated by
 * scripts/generate-bed.mjs — swap that one file for a licensed/AI track
 * later with zero code changes). The phase progression (near-silence,
 * sparse piano, broadening warmth, one small restrained swell, resolve) is
 * already baked into the bed itself, so this only needs a light overall
 * envelope to avoid clicks at the very start/end — not a second shaping
 * curve on top of it.
 */
export const MusicBed: React.FC = () => {
  const frame = useCurrentFrame();

  const volume = interpolate(
    frame,
    [0, 10, SCENES.scene7.end - 15, SCENES.scene7.end],
    [0, 0.9, 0.9, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' },
  );

  return <Audio src={staticFile('music/bed.wav')} volume={volume} />;
};
